language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3

os: linux

addons:
    apt:
        packages:
            - libxml2-dev
            - libxslt1-dev

install:
    - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export RUN_COVERAGE=true;
        pip install coverage codecov yapf pytest-cov;
      fi
    - pip install pytest lxml

script:
    - if [[ $RUN_COVERAGE == true ]]; then
        python -m pytest --cov=. --cov-config .coveragerc test/ && codecov;
        yapf -d *.py test/*.py;
      else
        python -m pytest test/;
      fi
